env:
  LANG: Go

task:
  image: golang:1.21

  matrix:
    # Testing
    - name: Tests
      env:
        matrix:
          - GOVERSION: 1.21
          - GOVERSION: 1.22
          - GOVERSION: 1.23
          - GOVERSION: 1.24
          - GOVERSION: 1.25
      container:
        image: golang:$GOVERSION
        additional_containers:
          - name: pg
            image: codercms/postgres-uint128:17-1.1.0
            port: 5432
            env:
              POSTGRES_PASSWORD: secret

      modules_cache:
        fingerprint_script: cat go.sum
        folder: $GOPATH/pkg/mod

      get_script: go get ./...
      build_script: go build ./...
      test_script: PGX_TEST_DATABASE=postgresql://postgres:secret@127.0.0.1:5432 go test ./... -timeout 2m -v

    # Linting
    - name: GolangCI Lint
      container:
        image: golangci/golangci-lint:v1.61.0

      modules_cache:
        fingerprint_script: cat go.sum
        folder: $GOPATH/pkg/mod

      get_script: go get ./...
      run_script: golangci-lint run -v --out-format json > lint-report.json

      always:
        golangci_artifacts:
          path: lint-report.json
          type: text/json
          format: golangci
